-- ═══════════════════════════════════════════════════════════════════════
-- Permission System v4 Migration
-- Run this on EXISTING databases to upgrade from the old RBAC system.
-- Safe to run multiple times (all statements are idempotent).
-- ═══════════════════════════════════════════════════════════════════════

SET NAMES utf8mb4;

-- 1. Ensure only Admin (roleId=1) and User (roleId=2) roles exist
INSERT INTO `roles` (`id`, `name`, `description`, `isSystem`) VALUES
  (1, 'Admin', 'مدير النظام — صلاحية كاملة تلقائياً', 1),
  (2, 'User', 'مستخدم — يحتاج صلاحيات صريحة', 1)
ON DUPLICATE KEY UPDATE `description`=VALUES(`description`);

-- 2. Migrate any non-admin users to roleId=2 (User)
--    Users with roleId=1 remain Admin. All others become User.
UPDATE `users` SET `roleId` = 2 WHERE `roleId` NOT IN (1, 2);

-- 3. Insert the full v4 permission catalog (idempotent via INSERT IGNORE)
INSERT IGNORE INTO `permissions` (`module`, `action`, `labelKey`) VALUES
  -- Employees
  ('employees', 'section.visible', 'employees.section.visible'),
  ('employees', 'view', 'employees.view'),
  ('employees', 'create', 'employees.create'),
  ('employees', 'edit', 'employees.edit'),
  ('employees', 'delete', 'employees.delete'),
  ('employees', 'archive', 'employees.archive'),
  ('employees', 'tab.basic', 'employees.tab.basic'),
  ('employees', 'tab.passport', 'employees.tab.passport'),
  ('employees', 'tab.contract', 'employees.tab.contract'),
  ('employees', 'tab.residency', 'employees.tab.residency'),
  ('employees', 'tab.insurances', 'employees.tab.insurances'),
  ('employees', 'tab.workStatus', 'employees.tab.workStatus'),
  ('employees', 'tab.phones', 'employees.tab.phones'),
  ('employees', 'tab.history', 'employees.tab.history'),
  ('employees', 'tab.documents', 'employees.tab.documents'),
  ('employees', 'field.nationality', 'employees.field.nationality'),
  ('employees', 'field.email', 'employees.field.email'),
  ('employees', 'field.phone', 'employees.field.phone'),
  ('employees', 'field.profilePhoto', 'employees.field.profilePhoto'),
  ('employees', 'field.passportNo', 'employees.field.passportNo'),
  ('employees', 'field.passportExpiry', 'employees.field.passportExpiry'),
  ('employees', 'field.nationalId', 'employees.field.nationalId'),
  ('employees', 'field.emiratesIdExpiry', 'employees.field.emiratesIdExpiry'),
  ('employees', 'field.salary', 'employees.field.salary'),
  ('employees', 'field.actualSalary', 'employees.field.actualSalary'),
  ('employees', 'field.contractDetails', 'employees.field.contractDetails'),
  ('employees', 'field.contractAllowances', 'employees.field.contractAllowances'),
  ('employees', 'field.insuranceHealth', 'employees.field.insuranceHealth'),
  ('employees', 'field.insuranceUnemployment', 'employees.field.insuranceUnemployment'),
  ('employees', 'field.workBranch', 'employees.field.workBranch'),
  ('employees', 'field.profession', 'employees.field.profession'),
  ('employees', 'field.loanDetails', 'employees.field.loanDetails'),
  ('employees', 'field.documentsLegal', 'employees.field.documentsLegal'),
  ('employees', 'field.documentsFinancial', 'employees.field.documentsFinancial'),
  ('employees', 'action.changeStatus', 'employees.action.changeStatus'),
  ('employees', 'action.transferBranch', 'employees.action.transferBranch'),
  ('employees', 'action.uploadDocs', 'employees.action.uploadDocs'),
  ('employees', 'action.deleteDocs', 'employees.action.deleteDocs'),
  ('employees', 'action.exportData', 'employees.action.exportData'),
  -- Branches
  ('branches', 'section.visible', 'branches.section.visible'),
  ('branches', 'view', 'branches.view'),
  ('branches', 'create', 'branches.create'),
  ('branches', 'edit', 'branches.edit'),
  ('branches', 'delete', 'branches.delete'),
  ('branches', 'tab.basic', 'branches.tab.basic'),
  ('branches', 'tab.licenses', 'branches.tab.licenses'),
  ('branches', 'tab.entity', 'branches.tab.entity'),
  ('branches', 'tab.employees', 'branches.tab.employees'),
  ('branches', 'tab.employers', 'branches.tab.employers'),
  ('branches', 'tab.history', 'branches.tab.history'),
  ('branches', 'tab.documents', 'branches.tab.documents'),
  ('branches', 'tab.phones', 'branches.tab.phones'),
  ('branches', 'field.branchType', 'branches.field.branchType'),
  ('branches', 'field.location', 'branches.field.location'),
  ('branches', 'field.contact', 'branches.field.contact'),
  ('branches', 'field.photo', 'branches.field.photo'),
  ('branches', 'field.address', 'branches.field.address'),
  ('branches', 'field.mapLink', 'branches.field.mapLink'),
  ('branches', 'field.workSchedule', 'branches.field.workSchedule'),
  ('branches', 'field.linkedBranch', 'branches.field.linkedBranch'),
  ('branches', 'field.tradeLicense', 'branches.field.tradeLicense'),
  ('branches', 'field.leaseContract', 'branches.field.leaseContract'),
  ('branches', 'field.leaseAmount', 'branches.field.leaseAmount'),
  ('branches', 'field.leaseSchedule', 'branches.field.leaseSchedule'),
  ('branches', 'field.taxIdentifiers', 'branches.field.taxIdentifiers'),
  ('branches', 'field.entityInfo', 'branches.field.entityInfo'),
  ('branches', 'field.employeeList', 'branches.field.employeeList'),
  ('branches', 'field.salaryInEmployeeTab', 'branches.field.salaryInEmployeeTab'),
  ('branches', 'field.employerList', 'branches.field.employerList'),
  ('branches', 'field.employerOwnership', 'branches.field.employerOwnership'),
  ('branches', 'action.uploadDocs', 'branches.action.uploadDocs'),
  ('branches', 'action.deleteDocs', 'branches.action.deleteDocs'),
  -- Housing
  ('housing', 'section.visible', 'housing.section.visible'),
  ('housing', 'view', 'housing.view'),
  ('housing', 'create', 'housing.create'),
  ('housing', 'edit', 'housing.edit'),
  ('housing', 'delete', 'housing.delete'),
  ('housing', 'tab.basic', 'housing.tab.basic'),
  ('housing', 'tab.contract', 'housing.tab.contract'),
  ('housing', 'tab.occupants', 'housing.tab.occupants'),
  ('housing', 'tab.phones', 'housing.tab.phones'),
  ('housing', 'tab.history', 'housing.tab.history'),
  ('housing', 'tab.documents', 'housing.tab.documents'),
  ('housing', 'field.contractAmount', 'housing.field.contractAmount'),
  ('housing', 'field.installments', 'housing.field.installments'),
  ('housing', 'field.occupantsList', 'housing.field.occupantsList'),
  ('housing', 'action.uploadDocs', 'housing.action.uploadDocs'),
  ('housing', 'action.deleteDocs', 'housing.action.deleteDocs'),
  -- Vehicles
  ('vehicles', 'section.visible', 'vehicles.section.visible'),
  ('vehicles', 'view', 'vehicles.view'),
  ('vehicles', 'create', 'vehicles.create'),
  ('vehicles', 'edit', 'vehicles.edit'),
  ('vehicles', 'delete', 'vehicles.delete'),
  ('vehicles', 'tab.basic', 'vehicles.tab.basic'),
  ('vehicles', 'tab.licenses', 'vehicles.tab.licenses'),
  ('vehicles', 'tab.permits', 'vehicles.tab.permits'),
  ('vehicles', 'tab.history', 'vehicles.tab.history'),
  ('vehicles', 'tab.documents', 'vehicles.tab.documents'),
  ('vehicles', 'field.insuranceDetails', 'vehicles.field.insuranceDetails'),
  ('vehicles', 'field.licenseDetails', 'vehicles.field.licenseDetails'),
  ('vehicles', 'field.permitDetails', 'vehicles.field.permitDetails'),
  ('vehicles', 'action.uploadDocs', 'vehicles.action.uploadDocs'),
  ('vehicles', 'action.deleteDocs', 'vehicles.action.deleteDocs'),
  -- Employers
  ('employers', 'section.visible', 'employers.section.visible'),
  ('employers', 'view', 'employers.view'),
  ('employers', 'create', 'employers.create'),
  ('employers', 'edit', 'employers.edit'),
  ('employers', 'delete', 'employers.delete'),
  ('employers', 'tab.basic', 'employers.tab.basic'),
  ('employers', 'tab.passportResidency', 'employers.tab.passportResidency'),
  ('employers', 'tab.branches', 'employers.tab.branches'),
  ('employers', 'tab.docs', 'employers.tab.docs'),
  ('employers', 'tab.history', 'employers.tab.history'),
  ('employers', 'field.passportDetails', 'employers.field.passportDetails'),
  ('employers', 'field.emiratesId', 'employers.field.emiratesId'),
  ('employers', 'field.branchLinks', 'employers.field.branchLinks'),
  ('employers', 'field.ownershipPercent', 'employers.field.ownershipPercent'),
  ('employers', 'action.uploadDocs', 'employers.action.uploadDocs'),
  ('employers', 'action.deleteDocs', 'employers.action.deleteDocs'),
  -- Phones
  ('phones', 'section.visible', 'phones.section.visible'),
  ('phones', 'view', 'phones.view'),
  ('phones', 'create', 'phones.create'),
  ('phones', 'edit', 'phones.edit'),
  ('phones', 'delete', 'phones.delete'),
  ('phones', 'tab.basic', 'phones.tab.basic'),
  ('phones', 'tab.history', 'phones.tab.history'),
  ('phones', 'tab.documents', 'phones.tab.documents'),
  ('phones', 'field.simDetails', 'phones.field.simDetails'),
  ('phones', 'field.assignedTo', 'phones.field.assignedTo'),
  ('phones', 'action.uploadDocs', 'phones.action.uploadDocs'),
  ('phones', 'action.deleteDocs', 'phones.action.deleteDocs'),
  -- Entities (Tax)
  ('entities', 'section.visible', 'entities.section.visible'),
  ('entities', 'view', 'entities.view'),
  ('entities', 'create', 'entities.create'),
  ('entities', 'edit', 'entities.edit'),
  ('entities', 'delete', 'entities.delete'),
  ('entities', 'tab.main', 'entities.tab.main'),
  ('entities', 'tab.branches', 'entities.tab.branches'),
  ('entities', 'tab.vat', 'entities.tab.vat'),
  ('entities', 'tab.corporate', 'entities.tab.corporate'),
  ('entities', 'tab.summary', 'entities.tab.summary'),
  ('entities', 'tab.documents', 'entities.tab.documents'),
  ('entities', 'tab.history', 'entities.tab.history'),
  ('entities', 'field.financialYear', 'entities.field.financialYear'),
  ('entities', 'field.taxPayments', 'entities.field.taxPayments'),
  ('entities', 'field.taxSummary', 'entities.field.taxSummary'),
  ('entities', 'action.uploadDocs', 'entities.action.uploadDocs'),
  ('entities', 'action.deleteDocs', 'entities.action.deleteDocs'),
  -- Documents
  ('documents', 'section.visible', 'documents.section.visible'),
  ('documents', 'view', 'documents.view'),
  ('documents', 'create', 'documents.create'),
  ('documents', 'edit', 'documents.edit'),
  ('documents', 'delete', 'documents.delete'),
  -- Settings
  ('settings', 'section.visible', 'settings.section.visible'),
  ('settings', 'view', 'settings.view'),
  ('settings', 'edit', 'settings.edit'),
  ('settings', 'sub.general', 'settings.sub.general'),
  ('settings', 'sub.language', 'settings.sub.language'),
  ('settings', 'sub.users', 'settings.sub.users'),
  ('settings', 'sub.permissions', 'settings.sub.permissions'),
  ('settings', 'sub.notifications', 'settings.sub.notifications'),
  ('settings', 'sub.database', 'settings.sub.database'),
  ('settings', 'sub.devices', 'settings.sub.devices'),
  ('settings', 'sub.backup', 'settings.sub.backup'),
  ('settings', 'users.view', 'settings.users.view'),
  ('settings', 'users.create', 'settings.users.create'),
  ('settings', 'users.edit', 'settings.users.edit'),
  ('settings', 'users.delete', 'settings.users.delete'),
  -- Logs
  ('logs', 'section.visible', 'logs.section.visible'),
  ('logs', 'view', 'logs.view');

-- 4. Clean up deprecated data (safe — these tables are no longer read)
-- Optionally clear role_permissions since admin gets everything in code
-- DELETE FROM role_permissions;  -- Uncomment if you want to clean up

-- 5. Bump permissionVersion to force all clients to reload
UPDATE `users` SET `permissionVersion` = `permissionVersion` + 1;
