export const FIELD_LABELS: Record<string, Record<string, { ar: string; en: string }>> = {
  employee: {
    name: { ar: 'الاسم', en: 'Name' },
    nationality: { ar: 'الجنسية', en: 'Nationality' },
    email: { ar: 'البريد الإلكتروني', en: 'Email' },
    phone: { ar: 'رقم الهاتف', en: 'Phone' },
    imagePath: { ar: 'صورة الموظف', en: 'Employee photo' },
    passportNumber: { ar: 'رقم الجواز', en: 'Passport number' },
    passportIssueDate: { ar: 'تاريخ إصدار الجواز', en: 'Passport issue date' },
    passportExpiryDate: { ar: 'تاريخ انتهاء الجواز', en: 'Passport expiry' },
    emiratesId: { ar: 'رقم الهوية الإماراتية', en: 'Emirates ID' },
    emiratesIdIssueDate: { ar: 'تاريخ إصدار الهوية', en: 'Emirates ID issue date' },
    emiratesIdExpiryDate: { ar: 'تاريخ انتهاء الهوية', en: 'Emirates ID expiry' },
    issueEmirate: { ar: 'إمارة الإصدار', en: 'Issue emirate' },
    contractType: { ar: 'نوع العقد', en: 'Contract type' },
    contractBranchId: { ar: 'فرع العقد', en: 'Contract branch' },
    workBranchId: { ar: 'فرع العمل', en: 'Work branch' },
    employerName: { ar: 'اسم صاحب العمل', en: 'Employer name' },
    establishmentNumber: { ar: 'رقم المنشأة', en: 'Establishment number' },
    immigrationEstablishmentNumber: { ar: 'رقم منشأة الجوازات', en: 'Immigration est. number' },
    professionKeys: { ar: 'المهنة', en: 'Profession' },
    professionCustomTitle: { ar: 'مسمى المهنة المخصص', en: 'Custom profession title' },
    professionPerContract: { ar: 'المهنة حسب العقد', en: 'Profession per contract' },
    contractIssueDate: { ar: 'تاريخ بداية العقد', en: 'Contract start date' },
    contractExpiryDate: { ar: 'تاريخ انتهاء العقد', en: 'Contract expiry' },
    basicSalary: { ar: 'الراتب الأساسي', en: 'Basic salary' },
    housingAllowance: { ar: 'بدل السكن', en: 'Housing allowance' },
    transportAllowance: { ar: 'بدل المواصلات', en: 'Transport allowance' },
    otherAllowances: { ar: 'بدلات أخرى', en: 'Other allowances' },
    status: { ar: 'الحالة', en: 'Status' },
    loanType: { ar: 'نوع الإعارة', en: 'Loan type' },
    targetEntityName: { ar: 'الجهة المستعيرة', en: 'Target entity' },
    loanExpiryDate: { ar: 'تاريخ انتهاء الإعارة', en: 'Loan expiry' },
    tempContractNumber: { ar: 'رقم العقد المؤقت', en: 'Temp contract number' },
    loanSalary: { ar: 'راتب الإعارة', en: 'Loan salary' },
    loanBranchId: { ar: 'فرع الإعارة', en: 'Loan branch' },
    loanProfession: { ar: 'مهنة الإعارة', en: 'Loan profession' },
    loanSubStatus: { ar: 'حالة الإعارة الفرعية', en: 'Loan sub-status' },
    actualSalary: { ar: 'الراتب الفعلي', en: 'Actual salary' },
    healthInsuranceEnabled: { ar: 'التأمين الصحي', en: 'Health insurance' },
    healthInsuranceProvider: { ar: 'مزود التأمين الصحي', en: 'Health insurance provider' },
    healthInsuranceIssueDate: { ar: 'تاريخ إصدار التأمين الصحي', en: 'Health ins. issue date' },
    healthInsuranceExpiryDate: { ar: 'تاريخ انتهاء التأمين الصحي', en: 'Health ins. expiry' },
    unemploymentInsuranceEnabled: { ar: 'تأمين التعطل', en: 'Unemployment insurance' },
    unemploymentInsuranceProvider: { ar: 'مزود تأمين التعطل', en: 'Unemp. ins. provider' },
    unemploymentInsuranceIssueDate: { ar: 'تاريخ إصدار تأمين التعطل', en: 'Unemp. ins. issue date' },
    unemploymentInsuranceExpiryDate: { ar: 'تاريخ انتهاء تأمين التعطل', en: 'Unemp. ins. expiry' },
  },
  branch: {
    name: { ar: 'اسم الفرع', en: 'Branch name' },
    nameEn: { ar: 'الاسم بالإنجليزية', en: 'English name' },
    phone: { ar: 'رقم الهاتف', en: 'Phone' },
    emirate: { ar: 'الإمارة', en: 'Emirate' },
    city: { ar: 'المدينة', en: 'City' },
    address: { ar: 'العنوان', en: 'Address' },
    branchType: { ar: 'نوع الفرع', en: 'Branch type' },
    linkedBranchId: { ar: 'الفرع المرتبط', en: 'Linked branch' },
    work24h: { ar: 'عمل 24 ساعة', en: '24h operation' },
    status: { ar: 'الحالة', en: 'Status' },
    googleMapUrl: { ar: 'رابط خرائط جوجل', en: 'Google Maps URL' },
    photoPath: { ar: 'صورة الفرع', en: 'Branch photo' },
    licenseNo: { ar: 'رقم الرخصة', en: 'License number' },
    tradeName: { ar: 'الاسم التجاري', en: 'Trade name' },
    tradeNameEn: { ar: 'الاسم التجاري بالإنجليزية', en: 'Trade name (EN)' },
    licenseIssueDate: { ar: 'تاريخ إصدار الرخصة', en: 'License issue date' },
    licenseExpiryDate: { ar: 'تاريخ انتهاء الرخصة', en: 'License expiry' },
    contractNo: { ar: 'رقم عقد الإيجار', en: 'Lease contract no.' },
    landlordName: { ar: 'اسم المؤجر', en: 'Landlord name' },
    leasePaymentType: { ar: 'طريقة الدفع', en: 'Payment type' },
    rentValue: { ar: 'قيمة الإيجار', en: 'Rent amount' },
    leaseIssueDate: { ar: 'تاريخ بداية الإيجار', en: 'Lease start' },
    leaseExpiryDate: { ar: 'تاريخ انتهاء الإيجار', en: 'Lease expiry' },
    isLegalEntity: { ar: 'كيان قانوني', en: 'Legal entity' },
    laborEstablishmentCardNo: { ar: 'رقم بطاقة منشأة العمل', en: 'Labor est. card no.' },
    immigrationCardNo: { ar: 'رقم بطاقة المنشأة', en: 'Immigration card no.' },
    immigrationCardIssueDate: { ar: 'تاريخ إصدار بطاقة المنشأة', en: 'Imm. card issue' },
    immigrationCardExpiryDate: { ar: 'تاريخ انتهاء بطاقة المنشأة', en: 'Imm. card expiry' },
  },
  vehicle: {
    plateNumber: { ar: 'رقم اللوحة', en: 'Plate number' },
    plateCode: { ar: 'رمز اللوحة', en: 'Plate code' },
    vehicleName: { ar: 'اسم المركبة', en: 'Vehicle name' },
    brand: { ar: 'الماركة', en: 'Brand' },
    model: { ar: 'الموديل', en: 'Model' },
    year: { ar: 'سنة الصنع', en: 'Year' },
    vehicleType: { ar: 'نوع المركبة', en: 'Vehicle type' },
    ownershipType: { ar: 'نوع الملكية', en: 'Ownership type' },
    branchId: { ar: 'الفرع', en: 'Branch' },
    ownerName: { ar: 'اسم المالك', en: 'Owner name' },
    issuePlace: { ar: 'مكان الإصدار', en: 'Issue place' },
    trafficNo: { ar: 'رقم المرور', en: 'Traffic number' },
    licenseRegDate: { ar: 'تاريخ تسجيل الرخصة', en: 'License reg. date' },
    licenseExpiryDate: { ar: 'تاريخ انتهاء الرخصة', en: 'License expiry' },
    insuranceCompany: { ar: 'شركة التأمين', en: 'Insurance company' },
    insuranceExpiryDate: { ar: 'تاريخ انتهاء التأمين', en: 'Insurance expiry' },
    insuranceType: { ar: 'نوع التأمين', en: 'Insurance type' },
    insurancePolicyNo: { ar: 'رقم وثيقة التأمين', en: 'Insurance policy no.' },
    photoPath: { ar: 'صورة المركبة', en: 'Vehicle photo' },
  },
  housing: {
    name: { ar: 'اسم الوحدة', en: 'Unit name' },
    housingType: { ar: 'نوع السكن', en: 'Housing type' },
    ownedBy: { ar: 'الملكية', en: 'Owned by' },
    emirate: { ar: 'الإمارة', en: 'Emirate' },
    address: { ar: 'العنوان', en: 'Address' },
    landlordName: { ar: 'اسم المؤجر', en: 'Landlord name' },
    tenantDisplayName: { ar: 'اسم المستأجر', en: 'Tenant name' },
    contractNo: { ar: 'رقم العقد', en: 'Contract no.' },
    contractIssue: { ar: 'تاريخ بداية العقد', en: 'Contract start' },
    contractExpiry: { ar: 'تاريخ انتهاء العقد', en: 'Contract expiry' },
    rentAmount: { ar: 'قيمة الإيجار', en: 'Rent amount' },
    paymentMethod: { ar: 'طريقة الدفع', en: 'Payment method' },
    leasePaymentType: { ar: 'نوع الدفع', en: 'Payment type' },
    branchId: { ar: 'الفرع', en: 'Branch' },
    employeeId: { ar: 'الموظف', en: 'Employee' },
    employerId: { ar: 'صاحب العمل', en: 'Employer' },
    otherPartyName: { ar: 'اسم الطرف الآخر', en: 'Other party name' },
  },
  employer: {
    fullName: { ar: 'الاسم الكامل', en: 'Full name' },
    fullNameEn: { ar: 'الاسم بالإنجليزية', en: 'English name' },
    nationality: { ar: 'الجنسية', en: 'Nationality' },
    phone: { ar: 'رقم الهاتف', en: 'Phone' },
    email: { ar: 'البريد الإلكتروني', en: 'Email' },
    occupation: { ar: 'المهنة', en: 'Occupation' },
    notes: { ar: 'ملاحظات', en: 'Notes' },
    passportNumber: { ar: 'رقم الجواز', en: 'Passport number' },
    passportIssueDate: { ar: 'تاريخ إصدار الجواز', en: 'Passport issue date' },
    passportExpiryDate: { ar: 'تاريخ انتهاء الجواز', en: 'Passport expiry' },
    passportCountry: { ar: 'بلد الجواز', en: 'Passport country' },
    emiratesId: { ar: 'رقم الهوية الإماراتية', en: 'Emirates ID' },
    emiratesIdIssueDate: { ar: 'تاريخ إصدار الهوية', en: 'Emirates ID issue date' },
    emiratesIdExpiryDate: { ar: 'تاريخ انتهاء الهوية', en: 'Emirates ID expiry' },
    issueEmirate: { ar: 'إمارة الإصدار', en: 'Issue emirate' },
    photoPath: { ar: 'صورة صاحب العمل', en: 'Employer photo' },
  },
  entity: {
    entityNickname: { ar: 'الاسم المختصر', en: 'Nickname' },
    mainBranchId: { ar: 'الفرع الرئيسي', en: 'Main branch' },
    name: { ar: 'اسم الكيان', en: 'Entity name' },
    nameEn: { ar: 'الاسم بالإنجليزية', en: 'English name' },
    registeredAddress: { ar: 'العنوان المسجل', en: 'Registered address' },
    contactNumber: { ar: 'رقم التواصل', en: 'Contact number' },
    trn: { ar: 'الرقم الضريبي', en: 'TRN' },
    vatEffectiveDate: { ar: 'تاريخ تسجيل الضريبة', en: 'VAT effective date' },
    vatFilingCycle: { ar: 'دورة التقديم الضريبي', en: 'VAT filing cycle' },
    corporateTaxRegistration: { ar: 'تسجيل ضريبة الشركات', en: 'Corp. tax registration' },
    corporateTaxEffectiveDate: { ar: 'تاريخ ضريبة الشركات', en: 'Corp. tax effective date' },
    financialYearEnd: { ar: 'نهاية السنة المالية', en: 'Financial year end' },
    notes: { ar: 'ملاحظات', en: 'Notes' },
  },
  phone: {
    phoneNumber: { ar: 'رقم الهاتف', en: 'Phone number' },
    provider: { ar: 'مزود الخدمة', en: 'Provider' },
    category: { ar: 'الفئة', en: 'Category' },
    numberType: { ar: 'نوع الرقم', en: 'Number type' },
    billAmount: { ar: 'مبلغ الفاتورة', en: 'Bill amount' },
    legalEntityId: { ar: 'الكيان القانوني', en: 'Legal entity' },
    registeredName: { ar: 'الاسم المسجل', en: 'Registered name' },
    assignedBranchId: { ar: 'الفرع المخصص', en: 'Assigned branch' },
    assignedEmployeeId: { ar: 'الموظف المخصص', en: 'Assigned employee' },
    assignedEmployerId: { ar: 'صاحب العمل المخصص', en: 'Assigned employer' },
    assignedHousingId: { ar: 'السكن المخصص', en: 'Assigned housing' },
    note: { ar: 'ملاحظة', en: 'Note' },
  },
};

const IMAGE_FIELDS = new Set([
  'imagePath', 'photoPath',
]);

export function isImageField(fieldName: string): boolean {
  return IMAGE_FIELDS.has(fieldName);
}

export function getFieldLabel(entityType: string, fieldName: string, lang: string): string {
  const labels = FIELD_LABELS[entityType]?.[fieldName];
  if (!labels) return fieldName;
  return lang === 'ar' ? labels.ar : labels.en;
}
